FROM mcr.microsoft.com/vscode/devcontainers/python:0-3.9

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN pipx uninstall black
RUN pipx uninstall flake8
RUN pipx uninstall pydocstyle
RUN pipx uninstall pycodestyle
RUN pipx uninstall mypy
RUN pipx uninstall pylint

WORKDIR /workspaces

COPY . ./glauth-ui

WORKDIR /workspaces/glauth-ui

RUN pip3 install -r requirements.txt --use-deprecated=legacy-resolver

# Set the default shell to bash instead of sh
ENV SHELL /bin/bash
